### ISSUE TITLE
Support for Gnome 42

### ISSUE THREAD

**Issue by mansoormemon** [GustavoPeredo/Big-Avatar-Gnome-Shell-Extension#10]
Kindly add support for gnome 42.

**Comment by djinnalexio** [comment]
Made a pull request for it.

To not have to wait for the update, go to the file `~/.local/share/gnome-shell/extensions/_big-avatar@gustavoperedo.org/metadata.json` and make this change: [link](https://github.com/GustavoPeredo/Big-Avatar-Gnome-Shell-Extension/pull/11/commits/fe795203d46c7767a7c82ae5458d8aab2a3c7ad4)

**Comment by GustavoPeredo** [comment]
Thanks!!
