### ISSUE TITLE
sizing the avatar

### ISSUE THREAD

**Issue by cristian-enve** [GustavoPeredo/Big-Avatar-Gnome-Shell-Extension#12]
Hi! would be great to have the choise to set the size of the avatar and the text.
Thanks!

**Comment by djinnalexio** [comment]
It used to be part of the original extension this project is forked from. Unfortunately, the feature had to be cut for the move to Gnome 40+.

Re-implementing it is already on the table. :thumbsup:

**Comment by djinnalexio** [comment]
[UserWidget script](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/userWidget.js)

I searched and found the source script of `UserWidget` which draws the extension. It seems that the way things are written doesn't allow for customization of the sizes or color (#5).

We could write our own `UserWidget.js` and implement all the customizations we want. However, doing so would add **a lot** of code. I personally don't think it's worth it if we want to keep the extension simple.

@GustavoPeredo Unless you wanna work on it too, I'm dropping size and color customization.
