### ISSUE TITLE
Update the extension on extensions.gnome.org

### ISSUE THREAD

**Issue by djinnalexio** [GustavoPeredo/Big-Avatar-Gnome-Shell-Extension#13]
Please update the build on [extensions.gnome.org](extensions.gnome.org) so that it shows up as compatible with Gnome 40 and later versions.

**Comment by GustavoPeredo** [comment]
There are a few updates to the code that are needed to update the extension.

Quoting from the extension review:
> 1. Please remove the Makefile: https://gjs.guide/extensions/review-guidelines/review-guidelines.html#don-t-include-unnecessary-files

> 2.  Please remove convenience.js and use getSettings() from ExtensionUtils instead of creating your own custom functions: https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/misc/extensionUtils.js

**Comment by djinnalexio** [comment]
First, is done. The second is not as straightforward but we'll see.

Edit:
Nevermind. They meant that `getSettings()` is already part of ExtensionUtils so no need to rewrite the function in `convenience.js` or `extension.js`.

**Comment by djinnalexio** [comment]
Almost there! Is anything else needed @GustavoPeredo?

**Comment by GustavoPeredo** [comment]
Yes, there are:

> 1. Prefs won't load. Because of the `convenience` import in line 8 (prefs.js). Also `Adw` doesn't exist in 40 and 41. So that will cause fatal error in prefs.js too.

> 2. Also do this in disable:

    ```js
    settings = null;
    bigAvatarItem = null;
    ```

> 3. Why are you using `this` for `_menuOpenStateChangedId` (extension.js). It's not in class.

I wished to help, hopefully in three weeks I can get back on track with collaborating with this extension

PS: You should be able to push to the repo directly now

**Comment by djinnalexio** [comment]
I've seen the permissions, thanks.

I'm still new to Javascript, I code at 3 in the morning, and both my VM and PC didn't call me out. So please bear with the weird lines (1 and 3).

As for the previous Gnomes, do you know a way to keep multiple versions on one machine besides adding more VMs?

**Comment by GustavoPeredo** [comment]
You might have some luck with [nix](https://discourse.nixos.org/t/managing-multiple-versions-of-node-js-with-nix/5425), but I think it might take too much of your time. Test with your GNOME only, this should cover most of the test cases.

**Comment by djinnalexio** [comment]
@GustavoPeredo 
I finished what was left. Anything else?
And here's an [icon](https://github.com/GustavoPeredo/Big-Avatar-Gnome-Shell-Extension/blob/master/assets/icon.png) for the the page.

**Comment by GustavoPeredo** [comment]
Thanks for the icon, looks great!

I'm having trouble starting my VM to test the extension, can you confirm if `_menuOpenStateChangedId` is needed?

**Comment by djinnalexio** [comment]
Just tried again. And no, it's not. I thought you meant to remove only `this` which is breaking, but removing the whole block doesn't seem to make a difference.

#16

```diff
//Run when extension is disabled
function disable() {
-    //Disconnect systemMenu
-    if (this._menuOpenStateChangedId) {
-        systemMenu.menu.disconnect(this._menuOpenStateChangedId);
-        this._menuOpenStateChangedId = 0;
-    }
    //Remove the bigAvatarItem
    bigAvatarItem.destroy();
    bigAvatarItem = null;
    //Clear settings
    settings.run_dispose();
    settings = null;
}
```

**Comment by djinnalexio** [comment]
@GustavoPeredo

Are there anymore changes required to push the version?

**Comment by GustavoPeredo** [comment]
Thanks for the changes, it's pending review.

**Comment by GustavoPeredo** [comment]
@djinnalexio There are more 🥲, if I have time and my vms work I'll try to fix them though.
```
1. Remove unnecessary line 71 (extension.js).

2. Remove `session-modes`:
    https://gjs.guide/extensions/review-guidelines/review-guidelines.html#metadata-json-must-be-well-formed

3. You cannot create objects in global scope (line 32 prefs.js).

4. No need to check in line 61 (prefs.js).
    `fillPreferencesWindow` only getting called on 42 and higher:
    https://gjs.guide/extensions/upgrading/gnome-shell-42.html#fillpreferenceswindow

5. Just a note, that's also GTK4 (prefs.js line 88)
    and that's GTK4 with LibAdwaita (prefs.js line 59).
```

**Comment by djinnalexio** [comment]
@GustavoPeredo Done. It was just more cleanup.

**Comment by GustavoPeredo** [comment]
You are a rock star! Thanks!

**Comment by GustavoPeredo** [comment]
It's published :tada:
