### ISSUE TITLE
Gnome 43

### ISSUE THREAD

**Issue by evgnor86** [GustavoPeredo/Big-Avatar-Gnome-Shell-Extension#20]
HI!

Main.panel.statusArea.aggregateMenu is undefined

**Comment by raihan2000** [comment]
@evgnor86 
for quick fixing you can replace aggregateMenu with quickSettings
just like ```Main.panel.statusArea.quickSettings.menu.addMenuItem(bigAvatarItem, 0);```

**Comment by evgnor86** [comment]
Thanks!
