### ISSUE TITLE
Username isn't displayed, text shows "Unkown" instead

### ISSUE THREAD

**Issue by broccoli-is-healthy** [GustavoPeredo/Big-Avatar-Gnome-Shell-Extension#3]
Gnome shell version - 3.38
Distro: Arch Linux

**Comment by GustavoPeredo** [comment]
Thank your for opening an issue! Could you please tell mode information? Maybe your account username and point gnome release (3.38.?)? I'll check it out then.

**Comment by broccoli-is-healthy** [comment]
The username is "r1amu" and release is 3.38.3

*And thank you!

**Comment by broccoli-is-healthy** [comment]
I probably found the issue. Disclaimer, I never made any Gnome extension and I don't know any JS. But it looks like you get the "real name" of the user instead of the "user name":

https://github.com/GustavoPeredo/Big-Avatar-Gnome-Shell-Extension/blob/e85debec0aaa22382cba64ffed63b9f67ee8937c/extension.js#L116-L120

And I never set my "real name" so that function returns "Unknown" instead.

**Comment by GustavoPeredo** [comment]
I kinda forgot about this project OwO. That makes a lot of sense, thanks for your comment! I think the best way to solve this would be to add an option on the extension settings to use user_name instead of real_name. Do you agree with this change? Do you have another idea?

**Comment by broccoli-is-healthy** [comment]
Yea I was thinking the same, it would be a great addition and solve this potential issue.

**Comment by GustavoPeredo** [comment]
Good news and bad news.
The bug should be fixed in the newest version, but there is no option to use user_name or real_name, it uses the default widget that comes with Gnome Shell (the one you see on GDM and login screen)...

**Comment by GustavoPeredo** [comment]
WIth the latest release, the extension should work with unnamed accounts (since it uses the same widget as the login manager) :)
