### ISSUE TITLE
Cannot run settings of this extension/Transition to user settings

### ISSUE THREAD

**Issue by ivanmood0** [GustavoPeredo/Big-Avatar-Gnome-Shell-Extension#4]
Currently in Ubuntu 20.04 cannot run settings of this extension.

I also be wanted that when clicking on the profile itself, the transition to user settings was made, in my opinion, it would be logical.

**Comment by GustavoPeredo** [comment]
Sorry, I don't really understand what you mean with "cannot run settings of this extension", could you elaborate?

**Comment by frosth555** [comment]
![Zrzut ekranu z 2021-03-26 11-27-10](https://user-images.githubusercontent.com/22305379/112618535-8539ef00-8e26-11eb-85cd-6d83d2d12c67.png)
result of trying tap 'configure' button:
![Zrzut ekranu z 2021-03-26 11-31-27](https://user-images.githubusercontent.com/22305379/112618837-da760080-8e26-11eb-9b32-f8f3b7a52830.png)

**Comment by ivanmood0** [comment]
> Sorry, I don't really understand what you mean with "cannot run settings of this extension", could you elaborate?

frosth555 answered above what I meant.

**Comment by GustavoPeredo** [comment]
@frosth555 @ivanmood0 thanks for reporting the issue, this is due to the migration to GTK4 and GNOME 40 and it's understandable that some users don't have access to it now. 

I have reverted the extension to version 6 until the release of the GNOME Extensions 40 (which should be available on flathub soon).

Thanks again for opening this ticket, if the extension doesn't downgrade automatically in your system, a simple reinstall via extensions.gnome.org should make it work again. If you habe any further doubts, feel free to ask them here

**Comment by ivanmood0** [comment]
> @frosth555 @ivanmood0 thanks for reporting the issue, this is due to the migration to GTK4 and GNOME 40 and it's understandable that some users don't have access to it now.
> 
> I have reverted the extension to version 6 until the release of the GNOME Extensions 40 (which should be available on flathub soon).
> 
> Thanks again for opening this ticket, if the extension doesn't downgrade automatically in your system, a simple reinstall via extensions.gnome.org should make it work again. If you habe any further doubts, feel free to ask them here

Thank you also for your quick response.
And what about the implementation of the function of going to the user settings when clicking on the profile itself? Are you planning to consider implementing such a feature? Perhaps even a separate switch, so that who does not need it, could leave the current variant.

**Comment by GustavoPeredo** [comment]
Yes, I'm planning to implement that! When I have some extra time I'll do that

**Comment by ivanmood0** [comment]
> Yes, I'm planning to implement that! When I have some extra time I'll do that

Oh, glad to hear that. Thx 🙃

**Comment by SaucySauce** [comment]
Close the issue.

**Comment by GustavoPeredo** [comment]
> Close the issue.

Soon,  I still haven't reimplemented

> the function of going to the user settings when clicking on the profile itself

**Comment by SaucySauce** [comment]
oh ok. didn't read that part.

**Comment by GustavoPeredo** [comment]
THere are two versions now (Automatically selected depending on GNOME Shell version), so this should be fixed

**Comment by galen1423** [comment]
Hi,

Settings window doesn't load correctly... same issue than @frosth555 @ivanmood0 
gnome-shell 3.38.4

**Comment by GustavoPeredo** [comment]
Thanks for telling me! I made a mistake when pushing the update. My bad. Should be fixed now (for real)

**Comment by galen1423** [comment]
Yes, this is **really** fix now with update. :)

Many thanks for your work.
