### ISSUE TITLE
Color of "User Label" is white (Gnome40, light theme whitesur)

### ISSUE THREAD

**Issue by frosth555** [GustavoPeredo/Big-Avatar-Gnome-Shell-Extension#5]
Hi, i have a small problem with bright color of username label, it's almost unvisible. 
IIRC at 3.38 change theme works corectly

thx

**Comment by GustavoPeredo** [comment]
Are you using the git or extensions.gnome.org version?

**Comment by frosth555** [comment]
Oh I've missed that info. 
ext version: git - c6b73f7, 
distro: archlinux

**Comment by GustavoPeredo** [comment]
I'm trying to find a solution to this issue, but doesn't seem very easy...
Do you know of any extension that either sets or gets which theme the user is using? That would of big help

**Comment by SaucySauce** [comment]
@frosth555 is this only happening with WhiteSur theme or all? If it's only with WhiteSur then it's probably a theme issue.

**Comment by GustavoPeredo** [comment]
> @frosth555 is this only happening with WhiteSur theme or all? If it's only with WhiteSur then it's probably a theme issue.

Yes and no, this bug will most likely occur with most white themes on version 8 of this extension. The bug is most likely occurring due to the styling of the login screen (where the username is written in white) and the styling of the panel (which is white in these themes).

The only things that come to my mind right now, would be to either:

a) Check if a user is using a light theme, if yes, then force override the font color to something else
b) Add a setting that allows overwriting of the label color
c) Or, return to how the extension used to work on versions < 40, where the image and label are two different widgets.

**Comment by frosth555** [comment]
First of all thanks for your time, unfortunately don't know how to determine which theme is used, but probably this is problem on theme side not that extension.
I've manually change color in gnome-shell.css and almost forget about problem :)
I'll ping author of whitesur theme and we will see.
Nothing to do here I believe. If you don't mind I'll close the issue.
@SaucySauce not only whitesur, light version of flat gnome remix is the same problem. But still this is theme problem,

**Comment by SaucySauce** [comment]
I can't test it out as I'm on Debian 11 with GS 3.38. Sorry.

**Comment by frosth555** [comment]
"b" option looks like need least effort, if theme set 'wrong' color, user can change it. sounds fair to me. 
"a" sounds too complicated a little bit. 
btw i can't find where color of user-widget-label is used besides big-avatar, I set it to pink and see nothing.

**Comment by GustavoPeredo** [comment]
> I set it to pink and see nothing.

It should appear on your lock screen. Do you mind sharing how you changed it?

**Comment by frosth555** [comment]
oh, it's simple. I found 
`.user-widget-label {
  color: COLOR FROM THEME;
}`
in 
`.themes/WhiteSur-light-blue/gnome-shell/gnome-shell.css`
and changed value to my preference

I've created simple bash script to uptade theme and applying patch for gnome-shell.css in the same time, It's primitive way but works.

**Comment by sergiotca** [comment]
> oh, it's simple. I found
> `.user-widget-label { color: COLOR FROM THEME; }`
> in
> `.themes/WhiteSur-light-blue/gnome-shell/gnome-shell.css`
> and changed value to my preference
> 
> I've created simple bash script to uptade theme and applying patch for gnome-shell.css in the same time, It's primitive way but works.

Hi, I tried your workaround but the issue persists:
![imagen](https://user-images.githubusercontent.com/41351896/124003216-4b840180-d99c-11eb-87bf-31157d6b4b1e.png)

The only difference is I'm using the [Prof-Gnome-theme](https://www.gnome-look.org/p/1334194/), which also has a light menu panel. 
I changed the "user-widget-label" (in `.themes/Prof-Gnome-Light-3.6/gnome-shell/gnome-shell.css`) to black (`#000000`) and then restarted the gnome shell by Alt+F2 and "r" then ↵. But no change. I've also disabled and re-enabled de extension. No luck either.

**Comment by frosth555** [comment]
I've just tried this theme and it works for me. Do you use gnome-shell-40?

**Comment by sergiotca** [comment]
> I've just tried this theme and it works for me. Do you use gnome-shell-40?

Nop, still on 3.38.4:
![imagen](https://user-images.githubusercontent.com/41351896/124330436-08b85a00-db53-11eb-994a-662c79b20f3c.png)
Is this no longer supported?

**Comment by frosth555** [comment]
On GS-3.38.x bigavatar works even better and I didn't need this hack before 40.x.

I tried it debian 11 (GS 3.38.5) and panel is all-dark
![gnome-shell-screenshot-YWEG60](https://user-images.githubusercontent.com/22305379/124347381-c0497c80-dbe4-11eb-9bb9-0c259932d208.png)
Are you sure you using Prof-Gnome-Light-3.6 for shell ?

**Comment by sergiotca** [comment]
Ok this is awkward, I had the User Themes Extension disabled... not my brightest moment  (-_-')
It's now working just fine, my apologies:
![image](https://user-images.githubusercontent.com/41351896/124499771-2f110c00-dd84-11eb-8194-4136b9e91270.png)
