### ISSUE TITLE
Bug: User name not centered

### ISSUE THREAD

**Issue by SaucySauce** [GustavoPeredo/Big-Avatar-Gnome-Shell-Extension#6]
Fedora 33, GS 3.38
![Screenshot from 2021-05-09 02-22-34](https://user-images.githubusercontent.com/38703177/117558487-6fe2f200-b06d-11eb-9e4a-cbb9b225c014.png)

**Comment by GustavoPeredo** [comment]
Damn, that's bad... I'm short on time this week, but will look into this issue later.

**Comment by SaucySauce** [comment]
Thanks.

**Comment by SaucySauce** [comment]
Fixed it.
![Screenshot from 2021-05-16 15-25-15](https://user-images.githubusercontent.com/38703177/118402780-ffcf0000-b65a-11eb-8f83-071384f6eea7.png)

**Comment by SaucySauce** [comment]
Can you create a separate branch with the last 3.38 compatible code so I can push a merge request with the fix?

**Comment by SaucySauce** [comment]
Nevermind. I've forked and reverted to 3.38 with the fix on my branch.

**Comment by SaucySauce** [comment]
Closing the issue.

**Comment by GustavoPeredo** [comment]
Thank you for solving this issue! Can I link your extension on the about section of BigAvatar on GNOME Extensions? So that users more easily find your extension?

**Comment by SaucySauce** [comment]
Absolutely. I won't be doing much to the code, just fixing little quirks when they're found. Will stay around until Debian 11 EOL.

**Comment by GustavoPeredo** [comment]
Awesome!
