### ISSUE TITLE
Enchancement: Equal distancing between margins

### ISSUE THREAD

**Issue by SaucySauce** [GustavoPeredo/Big-Avatar-Gnome-Shell-Extension#7]
![Screenshot from 2021-05-14 18-53-39](https://user-images.githubusercontent.com/38703177/118315972-bb6e2380-b4e5-11eb-85ba-5dcd3b9dc6e3.png)

**Comment by GustavoPeredo** [comment]
Thanks for your suggestion! It's really nice to hear some feedback.
If you are using a version of GNOME Shell prior to 40, then I'm sorry but there won't be new updates for the extension for you... In versions of the extension for GNOME Shell 40 or higher, I use the default Avatar widget, thus making the extensions cohesive with the rest of the shell. Thanks for your input once again

**Comment by SaucySauce** [comment]
I've been backporting some features to 38 on extensions I like that moved to GNOME 40. No worries.
